In [1]:
import pandas as pd
import pandas as pd, hashlib

# Analysis of 03 series csv

In [2]:
provisional_race_1_path = "barber-motorsports-park/barber/03_Provisional Results_Race 1_Anonymized.CSV"
race_results_1 = pd.read_csv(provisional_race_1_path, header=0,sep=";")

,POSITION,NUMBER,STATUS,LAPS,TOTAL_TIME,GAP_FIRST,GAP_PREVIOUS,FL_LAPNUM,FL_TIME,FL_KPH,...,ECM Car Id,ECM Brand Id,ECM Country Id,*Extra 7,*Extra 8,*Extra 9,Sort Key,DRIVER_*Extra 3,DRIVER_*Extra 4,DRIVER_*Extra 5
0,1,13,Classified,27,45:15.035,-,-,8,1:37.428,136.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,22,Classified,27,45:17.775,+2.740,+2.740,7,1:37.746,136.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,72,Classified,27,45:25.690,+10.655,+7.915,7,1:37.737,136.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,55,Classified,27,45:26.144,+11.109,+0.454,7,1:38.094,135.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,2,Classified,27,45:29.124,+14.089,+2.980,5,1:38.326,135.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,47,Classified,27,45:29.433,+14.398,+0.309,7,1:38.251,135.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,98,Classified,27,45:30.123,+15.088,+0.690,7,1:38.086,135.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,7,Classified,27,45:36.780,+21.745,+6.657,9,1:38.581,135.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,41,Classified,27,45:36.902,+21.867,+0.122,14,1:38.391,135.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,113,Classified,27,45:50.756,+35.721,+13.854,14,1:39.056,134.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,21,Classified,27,45:51.568,+36.533,+0.812,21,1:38.775,134.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12,111,Classified,27,45:51.893,+36.858,+0.325,24,1:38.944,134.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,31,Classified,27,45:52.233,+37.198,+0.340,7,1:38.542,135.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14,3,Classified,27,46:03.610,+48.575,+11.377,9,1:39.167,134.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,93,Classified,27,46:06.880,+51.845,+3.270,6,1:39.332,134.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,46,Classified,27,46:07.686,+52.651,+0.806,14,1:38.202,135.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,5,Classified,27,46:08.080,+53.045,+0.394,23,1:39.083,134.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,58,Classified,27,46:30.020,+1:14.985,+21.940,7,1:40.156,133.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19,80,Classified,27,46:34.789,+1:19.754,+4.769,5,1:39.807,133.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20,51,Classified,27,46:39.703,+1:24.668,+4.914,12,1:39.410,134.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21,18,Classified,26,45:28.789,1 Lap,1 Lap,19,1:41.379,131.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22,88,Classified,13,26:48.684,14 Laps,13 Laps,7,1:38.845,134.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
race_results_1.dropna(axis=1).columns

Index(['POSITION', 'NUMBER', 'STATUS', 'LAPS', 'TOTAL_TIME', 'GAP_FIRST',
       'GAP_PREVIOUS', 'FL_LAPNUM', 'FL_TIME', 'FL_KPH', 'CLASS', 'DIVISION',
       'VEHICLE'],
      dtype='object')

In [5]:
race_results_1.columns

Index(['POSITION', 'NUMBER', 'STATUS', 'LAPS', 'TOTAL_TIME', 'GAP_FIRST',
       'GAP_PREVIOUS', 'FL_LAPNUM', 'FL_TIME', 'FL_KPH', 'CLASS', 'GROUP',
       'DIVISION', 'VEHICLE', 'TIRES', 'ECM Participant Id', 'ECM Team Id',
       'ECM Category Id', 'ECM Car Id', 'ECM Brand Id', 'ECM Country Id',
       '*Extra 7', '*Extra 8', '*Extra 9', 'Sort Key', 'DRIVER_*Extra 3',
       'DRIVER_*Extra 4', 'DRIVER_*Extra 5'],
      dtype='object')

In [8]:
race_results_1[['POSITION', 'NUMBER','LAPS','FL_LAPNUM','FL_TIME','FL_KPH','TOTAL_TIME','GAP_FIRST','GAP_PREVIOUS']]

,POSITION,NUMBER,LAPS,FL_LAPNUM,FL_TIME,FL_KPH,TOTAL_TIME,GAP_FIRST,GAP_PREVIOUS
0,1,13,27,8,1:37.428,136.8,45:15.035,-,-
1,2,22,27,7,1:37.746,136.3,45:17.775,+2.740,+2.740
2,3,72,27,7,1:37.737,136.3,45:25.690,+10.655,+7.915
3,4,55,27,7,1:38.094,135.8,45:26.144,+11.109,+0.454
4,5,2,27,5,1:38.326,135.5,45:29.124,+14.089,+2.980
5,6,47,27,7,1:38.251,135.6,45:29.433,+14.398,+0.309
6,7,98,27,7,1:38.086,135.9,45:30.123,+15.088,+0.690
7,8,7,27,9,1:38.581,135.2,45:36.780,+21.745,+6.657
8,9,41,27,14,1:38.391,135.4,45:36.902,+21.867,+0.122
9,10,113,27,14,1:39.056,134.5,45:50.756,+35.721,+13.854
10,11,21,27,21,1:38.775,134.9,45:51.568,+36.533,+0.812
11,12,111,27,24,1:38.944,134.7,45:51.893,+36.858,+0.325
12,13,31,27,7,1:38.542,135.2,45:52.233,+37.198,+0.340
13,14,3,27,9,1:39.167,134.4,46:03.610,+48.575,+11.377
14,15,93,27,6,1:39.332,134.1,46:06.880,+51.845,+3.270
15,16,46,27,14,1:38.202,135.7,46:07.686,+52.651,+0.806
16,17,5,27,23,1:39.083,134.5,46:08.080,+53.045,+0.394
17,18,58,27,7,1:40.156,133.0,46:30.020,+1:14.985,+21.940
18,19,80,27,5,1:39.807,133.5,46:34.789,+1:19.754,+4.769
19,20,51,27,12,1:39.410,134.0,46:39.703,+1:24.668,+4.914
20,21,18,26,19,1:41.379,131.4,45:28.789,1 Lap,1 Lap
21,22,88,13,7,1:38.845,134.8,26:48.684,14 Laps,13 Laps

In [87]:
race_results_1['race'] = 1
race_results_1 = race_results_1[['POSITION', 'NUMBER','LAPS','FL_LAPNUM','FL_TIME','FL_KPH','TOTAL_TIME','GAP_FIRST','GAP_PREVIOUS','VEHICLE','TIRES','DIVISION','CLASS']]
race_results_1

,POSITION,NUMBER,LAPS,FL_LAPNUM,FL_TIME,FL_KPH,TOTAL_TIME,GAP_FIRST,GAP_PREVIOUS,VEHICLE,TIRES,DIVISION,CLASS
0,1,13,27,8,1:37.428,136.8,45:15.035,-,-,Toyota GR86,NaN,GR Cup,Am
1,2,22,27,7,1:37.746,136.3,45:17.775,+2.740,+2.740,Toyota GR86,NaN,GR Cup,Am
2,3,72,27,7,1:37.737,136.3,45:25.690,+10.655,+7.915,Toyota GR86,NaN,GR Cup,Am
3,4,55,27,7,1:38.094,135.8,45:26.144,+11.109,+0.454,Toyota GR86,NaN,GR Cup,Am
4,5,2,27,5,1:38.326,135.5,45:29.124,+14.089,+2.980,Toyota GR86,NaN,GR Cup,Am
5,6,47,27,7,1:38.251,135.6,45:29.433,+14.398,+0.309,Toyota GR86,NaN,GR Cup,Am
6,7,98,27,7,1:38.086,135.9,45:30.123,+15.088,+0.690,Toyota GR86,NaN,GR Cup,Am
7,8,7,27,9,1:38.581,135.2,45:36.780,+21.745,+6.657,Toyota GR86,NaN,GR Cup,Am
8,9,41,27,14,1:38.391,135.4,45:36.902,+21.867,+0.122,Toyota GR86,NaN,GR Cup,Am
9,10,113,27,14,1:39.056,134.5,45:50.756,+35.721,+13.854,Toyota GR86,NaN,GR Cup,Am
10,11,21,27,21,1:38.775,134.9,45:51.568,+36.533,+0.812,Toyota GR86,NaN,GR Cup,Am
11,12,111,27,24,1:38.944,134.7,45:51.893,+36.858,+0.325,Toyota GR86,NaN,GR Cup,Am
12,13,31,27,7,1:38.542,135.2,45:52.233,+37.198,+0.340,Toyota GR86,NaN,GR Cup,Am
13,14,3,27,9,1:39.167,134.4,46:03.610,+48.575,+11.377,Toyota GR86,NaN,GR Cup,Am
14,15,93,27,6,1:39.332,134.1,46:06.880,+51.845,+3.270,Toyota GR86,NaN,GR Cup,Am
15,16,46,27,14,1:38.202,135.7,46:07.686,+52.651,+0.806,Toyota GR86,NaN,GR Cup,Am
16,17,5,27,23,1:39.083,134.5,46:08.080,+53.045,+0.394,Toyota GR86,NaN,GR Cup,Am
17,18,58,27,7,1:40.156,133.0,46:30.020,+1:14.985,+21.940,Toyota GR86,NaN,GR Cup,Am
18,19,80,27,5,1:39.807,133.5,46:34.789,+1:19.754,+4.769,Toyota GR86,NaN,GR Cup,Am
19,20,51,27,12,1:39.410,134.0,46:39.703,+1:24.668,+4.914,Toyota GR86,NaN,GR Cup,Am
20,21,18,26,19,1:41.379,131.4,45:28.789,1 Lap,1 Lap,Toyota GR86,NaN,GR Cup,Am
21,22,88,13,7,1:38.845,134.8,26:48.684,14 Laps,13 Laps,Toyota GR86,NaN,GR Cup,Am

In [88]:
provisional_race_2_path = "barber-motorsports-park/barber/03_Provisional Results_Race 2_Anonymized.CSV"
race_results_2 = pd.read_csv( provisional_race_2_path,header=0,sep=";")

In [89]:
race_results_2['race'] = 2
race_results_2 = race_results_2[['POSITION', 'NUMBER','LAPS','FL_LAPNUM','FL_TIME','FL_KPH','TOTAL_TIME','GAP_FIRST','GAP_PREVIOUS','VEHICLE','TIRES','DIVISION','CLASS']]
race_results_2

,POSITION,NUMBER,LAPS,FL_LAPNUM,FL_TIME,FL_KPH,TOTAL_TIME,GAP_FIRST,GAP_PREVIOUS,VEHICLE,TIRES,DIVISION,CLASS
0,1,13,28,2,1:37.350,136.9,45:37.014,-,-,Toyota GR86,NaN,GR Cup,Am
1,2,22,28,11,1:37.304,136.9,45:37.248,+0.234,+0.234,Toyota GR86,NaN,GR Cup,Am
2,3,2,28,17,1:37.678,136.4,45:53.320,+16.306,+16.072,Toyota GR86,NaN,GR Cup,Am
3,4,72,28,14,1:37.945,136.0,45:57.708,+20.694,+4.388,Toyota GR86,NaN,GR Cup,Am
4,5,46,28,13,1:37.910,136.1,45:57.899,+20.885,+0.191,Toyota GR86,NaN,GR Cup,Am
5,6,47,28,5,1:37.968,136.0,46:01.221,+24.207,+3.322,Toyota GR86,NaN,GR Cup,Am
6,7,21,28,16,1:38.074,135.9,46:02.498,+25.484,+1.277,Toyota GR86,NaN,GR Cup,Am
7,8,7,28,12,1:38.237,135.6,46:08.145,+31.131,+5.647,Toyota GR86,NaN,GR Cup,Am
8,9,88,28,8,1:38.176,135.7,46:08.355,+31.341,+0.210,Toyota GR86,NaN,GR Cup,Am
9,10,111,28,7,1:38.304,135.6,46:09.061,+32.047,+0.706,Toyota GR86,NaN,GR Cup,Am
10,11,5,28,17,1:38.185,135.7,46:10.064,+33.050,+1.003,Toyota GR86,NaN,GR Cup,Am
11,12,41,28,19,1:37.945,136.0,46:27.640,+50.626,+17.576,Toyota GR86,NaN,GR Cup,Am
12,13,51,28,5,1:38.345,135.5,46:28.569,+51.555,+0.929,Toyota GR86,NaN,GR Cup,Am
13,14,3,28,6,1:38.920,134.7,46:30.258,+53.244,+1.689,Toyota GR86,NaN,GR Cup,Am
14,15,98,28,15,1:37.693,136.4,46:55.198,+1:18.184,+24.940,Toyota GR86,NaN,GR Cup,Am
15,16,18,27,7,1:40.296,132.9,45:46.905,1 Lap,1 Lap,Toyota GR86,NaN,GR Cup,Am
16,17,31,27,17,1:37.882,136.1,46:10.709,1 Lap,+23.804,Toyota GR86,NaN,GR Cup,Am
17,18,80,27,7,1:39.010,134.6,46:45.198,1 Lap,+34.489,Toyota GR86,NaN,GR Cup,Am
18,19,58,27,7,1:38.840,134.8,47:11.758,1 Lap,+26.560,Toyota GR86,NaN,GR Cup,Am
19,20,55,26,4,1:37.792,136.3,42:37.902,2 Laps,1 Lap,Toyota GR86,NaN,GR Cup,Am
20,21,93,24,13,1:38.961,134.7,46:38.638,4 Laps,2 Laps,Toyota GR86,NaN,GR Cup,Am
21,22,113,24,13,1:38.382,135.4,47:35.196,4 Laps,+56.558,Toyota GR86,NaN,GR Cup,Am

In [90]:

official_race_2_results_path = "barber-motorsports-park/barber/03_Results GR Cup Race 2 Official_Anonymized.CSV"
official_race_2_results = pd.read_csv(official_race_2_results_path, header=0,sep=";")

In [92]:
official_race_2_results[['POSITION', 'NUMBER','LAPS','FL_LAPNUM','FL_TIME','FL_KPH','TOTAL_TIME','GAP_FIRST','GAP_PREVIOUS','VEHICLE','TIRES','DIVISION','CLASS']]

,POSITION,NUMBER,LAPS,FL_LAPNUM,FL_TIME,FL_KPH,TOTAL_TIME,GAP_FIRST,GAP_PREVIOUS,VEHICLE,TIRES,DIVISION,CLASS
0,1,13,28,2,1:37.350,136.9,45:37.014,-,-,Toyota GR86,NaN,GR Cup,Am
1,2,22,28,11,1:37.304,136.9,45:37.248,+0.234,+0.234,Toyota GR86,NaN,GR Cup,Am
2,3,2,28,17,1:37.678,136.4,45:53.320,+16.306,+16.072,Toyota GR86,NaN,GR Cup,Am
3,4,72,28,14,1:37.945,136.0,45:57.708,+20.694,+4.388,Toyota GR86,NaN,GR Cup,Am
4,5,46,28,13,1:37.910,136.1,45:57.899,+20.885,+0.191,Toyota GR86,NaN,GR Cup,Am
5,6,47,28,5,1:37.968,136.0,46:01.221,+24.207,+3.322,Toyota GR86,NaN,GR Cup,Am
6,7,21,28,16,1:38.074,135.9,46:02.498,+25.484,+1.277,Toyota GR86,NaN,GR Cup,Am
7,8,7,28,12,1:38.237,135.6,46:08.145,+31.131,+5.647,Toyota GR86,NaN,GR Cup,Am
8,9,88,28,8,1:38.176,135.7,46:08.355,+31.341,+0.210,Toyota GR86,NaN,GR Cup,Am
9,10,111,28,7,1:38.304,135.6,46:09.061,+32.047,+0.706,Toyota GR86,NaN,GR Cup,Am
10,11,5,28,17,1:38.185,135.7,46:10.064,+33.050,+1.003,Toyota GR86,NaN,GR Cup,Am
11,12,41,28,19,1:37.945,136.0,46:27.640,+50.626,+17.576,Toyota GR86,NaN,GR Cup,Am
12,13,51,28,5,1:38.345,135.5,46:28.569,+51.555,+0.929,Toyota GR86,NaN,GR Cup,Am
13,14,3,28,6,1:38.920,134.7,46:30.258,+53.244,+1.689,Toyota GR86,NaN,GR Cup,Am
14,15,98,28,15,1:37.693,136.4,46:55.198,+1:18.184,+24.940,Toyota GR86,NaN,GR Cup,Am
15,16,18,27,7,1:40.296,132.9,45:46.905,1 Lap,1 Lap,Toyota GR86,NaN,GR Cup,Am
16,17,31,27,17,1:37.882,136.1,46:10.709,1 Lap,+23.804,Toyota GR86,NaN,GR Cup,Am
17,18,80,27,7,1:39.010,134.6,46:45.198,1 Lap,+34.489,Toyota GR86,NaN,GR Cup,Am
18,19,58,27,7,1:38.840,134.8,47:11.758,1 Lap,+26.560,Toyota GR86,NaN,GR Cup,Am
19,20,55,26,4,1:37.792,136.3,42:37.902,2 Laps,1 Lap,Toyota GR86,NaN,GR Cup,Am
20,21,93,24,13,1:38.961,134.7,46:38.638,4 Laps,2 Laps,Toyota GR86,NaN,GR Cup,Am
21,22,113,24,13,1:38.382,135.4,47:35.196,4 Laps,+56.558,Toyota GR86,NaN,GR Cup,Am

In [93]:

A,B=provisional_race_2_path, official_race_2_results_path
raw_same = hashlib.sha256(open(A,'rb').read()).hexdigest()==hashlib.sha256(open(B,'rb').read()).hexdigest()
norm=lambda d: d.applymap(lambda x: str(x).strip() if isinstance(x,str) else x).reindex(sorted(d.columns),axis=1).sort_values(by=sorted(d.columns)).reset_index(drop=True)
sem_same = hashlib.sha256(norm(pd.read_csv(A, sep=None, engine='python')).to_csv(index=False).encode()).hexdigest()==hashlib.sha256(norm(pd.read_csv(B, sep=None, engine='python')).to_csv(index=False).encode()).hexdigest(); print({'raw_same':raw_same,'semantic_same':sem_same})

{'raw_same': True, 'semantic_same': True}

C:\Users\user\AppData\Local\Temp\ipykernel_98448\3252750323.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  norm=lambda d: d.applymap(lambda x: str(x).strip() if isinstance(x,str) else x).reindex(sorted(d.columns),axis=1).sort_values(by=sorted(d.columns)).reset_index(drop=True)
C:\Users\user\AppData\Local\Temp\ipykernel_98448\3252750323.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  norm=lambda d: d.applymap(lambda x: str(x).strip() if isinstance(x,str) else x).reindex(sorted(d.columns),axis=1).sort_values(by=sorted(d.columns)).reset_index(drop=True)

# Conclusions

#### for 03 series of files, provisional race 2 and official 2 are same as per the checksum validation,

In [96]:
race_merged = pd.concat([race_results_2,official_race_2_results],ignore_index=True)
race_merged.dropna(axis=1,inplace=True)

race_merged.to_csv("final_race_merged.csv", index=False)

# Analysis of 05 series

In [95]:
class_race_1_path = "barber-motorsports-park/barber/05_Provisional Results by Class_Race 1_Anonymized.CSV"
class_race_2_path = "barber-motorsports-park/barber/05_Provisional Results by Class_Race 2_Anonymized.CSV"
official_race_class_1_results_path = "barber-motorsports-park/barber/05_Results by Class GR Cup Race 1 Official_Anonymized.CSV"

In [99]:
class_race_1 = pd.read_csv(class_race_1_path,sep=';')
class_race_1

,CLASS_TYPE,POS,PIC,NUMBER,VEHICLE,LAPS,ELAPSED,GAP_FIRST,GAP_PREVIOUS,BEST_LAP_NUM,BEST_LAP_TIME,BEST_LAP_KPH
0,Am,1,1,13,Toyota GR86,27,45:15.035,NaN,NaN,8,1:37.428,136.8
1,Am,2,2,22,Toyota GR86,27,45:17.775,+2.740,+2.740,7,1:37.746,136.3
2,Am,3,3,72,Toyota GR86,27,45:25.690,+10.655,+7.915,7,1:37.737,136.3
3,Am,4,4,55,Toyota GR86,27,45:26.144,+11.109,+0.454,7,1:38.094,135.8
4,Am,5,5,2,Toyota GR86,27,45:29.124,+14.089,+2.980,5,1:38.326,135.5
5,Am,6,6,47,Toyota GR86,27,45:29.433,+14.398,+0.309,7,1:38.251,135.6
6,Am,7,7,98,Toyota GR86,27,45:30.123,+15.088,+0.690,7,1:38.086,135.9
7,Am,8,8,7,Toyota GR86,27,45:36.780,+21.745,+6.657,9,1:38.581,135.2
8,Am,9,9,41,Toyota GR86,27,45:36.902,+21.867,+0.122,14,1:38.391,135.4
9,Am,10,10,113,Toyota GR86,27,45:50.756,+35.721,+13.854,14,1:39.056,134.5
10,Am,11,11,21,Toyota GR86,27,45:51.568,+36.533,+0.812,21,1:38.775,134.9
11,Am,12,12,111,Toyota GR86,27,45:51.893,+36.858,+0.325,24,1:38.944,134.7
12,Am,13,13,31,Toyota GR86,27,45:52.233,+37.198,+0.340,7,1:38.542,135.2
13,Am,14,14,3,Toyota GR86,27,46:03.610,+48.575,+11.377,9,1:39.167,134.4
14,Am,15,15,93,Toyota GR86,27,46:06.880,+51.845,+3.270,6,1:39.332,134.1
15,Am,16,16,46,Toyota GR86,27,46:07.686,+52.651,+0.806,14,1:38.202,135.7
16,Am,17,17,5,Toyota GR86,27,46:08.080,+53.045,+0.394,23,1:39.083,134.5
17,Am,18,18,58,Toyota GR86,27,46:30.020,+1'14.985,+21.940,7,1:40.156,133.0
18,Am,19,19,80,Toyota GR86,27,46:34.789,+1'19.754,+4.769,5,1:39.807,133.5
19,Am,20,20,51,Toyota GR86,27,46:39.703,+1'24.668,+4.914,12,1:39.410,134.0
20,Am,21,21,18,Toyota GR86,26,45:28.789,1 Laps,1 Laps,19,1:41.379,131.4
21,Am,22,22,88,Toyota GR86,13,26:48.684,14 Laps,13 Laps,7,1:38.845,134.8

In [74]:
A,B=class_race_1_path, official_race_class_1_results_path
raw_same = hashlib.sha256(open(A,'rb').read()).hexdigest()==hashlib.sha256(open(B,'rb').read()).hexdigest()
norm=lambda d: d.applymap(lambda x: str(x).strip() if isinstance(x,str) else x).reindex(sorted(d.columns),axis=1).sort_values(by=sorted(d.columns)).reset_index(drop=True)
sem_same = hashlib.sha256(norm(pd.read_csv(A, sep=None, engine='python')).to_csv(index=False).encode()).hexdigest()==hashlib.sha256(norm(pd.read_csv(B, sep=None, engine='python')).to_csv(index=False).encode()).hexdigest(); print({'raw_same':raw_same,'semantic_same':sem_same})

{'raw_same': True, 'semantic_same': True}

C:\Users\user\AppData\Local\Temp\ipykernel_98448\4175036453.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  norm=lambda d: d.applymap(lambda x: str(x).strip() if isinstance(x,str) else x).reindex(sorted(d.columns),axis=1).sort_values(by=sorted(d.columns)).reset_index(drop=True)
C:\Users\user\AppData\Local\Temp\ipykernel_98448\4175036453.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  norm=lambda d: d.applymap(lambda x: str(x).strip() if isinstance(x,str) else x).reindex(sorted(d.columns),axis=1).sort_values(by=sorted(d.columns)).reset_index(drop=True)

In [75]:
class_race_2 = pd.read_csv(class_race_2_path,sep=';')
class_race_2

,CLASS_TYPE,POS,PIC,NUMBER,VEHICLE,LAPS,ELAPSED,GAP_FIRST,GAP_PREVIOUS,BEST_LAP_NUM,BEST_LAP_TIME,BEST_LAP_KPH
0,Am,1,1,13,Toyota GR86,28,45:37.014,NaN,NaN,2,1:37.350,136.9
1,Am,2,2,22,Toyota GR86,28,45:37.248,+0.234,+0.234,11,1:37.304,136.9
2,Am,3,3,2,Toyota GR86,28,45:53.320,+16.306,+16.072,17,1:37.678,136.4
3,Am,4,4,72,Toyota GR86,28,45:57.708,+20.694,+4.388,14,1:37.945,136.0
4,Am,5,5,46,Toyota GR86,28,45:57.899,+20.885,+0.191,13,1:37.910,136.1
5,Am,6,6,47,Toyota GR86,28,46:01.221,+24.207,+3.322,5,1:37.968,136.0
6,Am,7,7,21,Toyota GR86,28,46:02.498,+25.484,+1.277,16,1:38.074,135.9
7,Am,8,8,7,Toyota GR86,28,46:08.145,+31.131,+5.647,12,1:38.237,135.6
8,Am,9,9,88,Toyota GR86,28,46:08.355,+31.341,+0.210,8,1:38.176,135.7
9,Am,10,10,111,Toyota GR86,28,46:09.061,+32.047,+0.706,7,1:38.304,135.6
10,Am,11,11,5,Toyota GR86,28,46:10.064,+33.050,+1.003,17,1:38.185,135.7
11,Am,12,12,41,Toyota GR86,28,46:27.640,+50.626,+17.576,19,1:37.945,136.0
12,Am,13,13,51,Toyota GR86,28,46:28.569,+51.555,+0.929,5,1:38.345,135.5
13,Am,14,14,3,Toyota GR86,28,46:30.258,+53.244,+1.689,6,1:38.920,134.7
14,Am,15,15,98,Toyota GR86,28,46:55.198,+1'18.184,+24.940,15,1:37.693,136.4
15,Am,16,16,18,Toyota GR86,27,45:46.905,1 Laps,1 Laps,7,1:40.296,132.9
16,Am,17,17,31,Toyota GR86,27,46:10.709,1 Laps,+23.804,17,1:37.882,136.1
17,Am,18,18,80,Toyota GR86,27,46:45.198,1 Laps,+34.489,7,1:39.010,134.6
18,Am,19,19,58,Toyota GR86,27,47:11.758,1 Laps,+26.560,7,1:38.840,134.8
19,Am,20,20,55,Toyota GR86,26,42:37.902,2 Laps,1 Laps,4,1:37.792,136.3
20,Am,21,21,93,Toyota GR86,24,46:38.638,4 Laps,2 Laps,13,1:38.961,134.7
21,Am,22,22,113,Toyota GR86,24,47:35.196,4 Laps,+56.558,13,1:38.382,135.4

In [77]:
official_race_class_1_results = pd.read_csv(official_race_class_1_results_path,sep=';')
official_race_class_1_results

,CLASS_TYPE,POS,PIC,NUMBER,VEHICLE,LAPS,ELAPSED,GAP_FIRST,GAP_PREVIOUS,BEST_LAP_NUM,BEST_LAP_TIME,BEST_LAP_KPH
0,Am,1,1,13,Toyota GR86,27,45:15.035,NaN,NaN,8,1:37.428,136.8
1,Am,2,2,22,Toyota GR86,27,45:17.775,+2.740,+2.740,7,1:37.746,136.3
2,Am,3,3,72,Toyota GR86,27,45:25.690,+10.655,+7.915,7,1:37.737,136.3
3,Am,4,4,55,Toyota GR86,27,45:26.144,+11.109,+0.454,7,1:38.094,135.8
4,Am,5,5,2,Toyota GR86,27,45:29.124,+14.089,+2.980,5,1:38.326,135.5
5,Am,6,6,47,Toyota GR86,27,45:29.433,+14.398,+0.309,7,1:38.251,135.6
6,Am,7,7,98,Toyota GR86,27,45:30.123,+15.088,+0.690,7,1:38.086,135.9
7,Am,8,8,7,Toyota GR86,27,45:36.780,+21.745,+6.657,9,1:38.581,135.2
8,Am,9,9,41,Toyota GR86,27,45:36.902,+21.867,+0.122,14,1:38.391,135.4
9,Am,10,10,113,Toyota GR86,27,45:50.756,+35.721,+13.854,14,1:39.056,134.5
10,Am,11,11,21,Toyota GR86,27,45:51.568,+36.533,+0.812,21,1:38.775,134.9
11,Am,12,12,111,Toyota GR86,27,45:51.893,+36.858,+0.325,24,1:38.944,134.7
12,Am,13,13,31,Toyota GR86,27,45:52.233,+37.198,+0.340,7,1:38.542,135.2
13,Am,14,14,3,Toyota GR86,27,46:03.610,+48.575,+11.377,9,1:39.167,134.4
14,Am,15,15,93,Toyota GR86,27,46:06.880,+51.845,+3.270,6,1:39.332,134.1
15,Am,16,16,46,Toyota GR86,27,46:07.686,+52.651,+0.806,14,1:38.202,135.7
16,Am,17,17,5,Toyota GR86,27,46:08.080,+53.045,+0.394,23,1:39.083,134.5
17,Am,18,18,58,Toyota GR86,27,46:30.020,+1'14.985,+21.940,7,1:40.156,133.0
18,Am,19,19,80,Toyota GR86,27,46:34.789,+1'19.754,+4.769,5,1:39.807,133.5
19,Am,20,20,51,Toyota GR86,27,46:39.703,+1'24.668,+4.914,12,1:39.410,134.0
20,Am,21,21,18,Toyota GR86,26,45:28.789,1 Laps,1 Laps,19,1:41.379,131.4
21,Am,22,22,88,Toyota GR86,13,26:48.684,14 Laps,13 Laps,7,1:38.845,134.8

In [ ]:
# As expected, the provisional results by class race and official are same files.

# INSIGHTS
# the unique identifier for a winning car is NUMBER, endurance data also confirms the same -> 
# [  3, 111, 113,  13,  18,   2,  21,  22,  31,  41,  46,  47, 5, 51,  55,  58,   7,  72,  80,  88,  93,  98]